// ChargeCardActivity.ts — generated by `street make:activity ChargeCard`.
import type { Activity } from "@streetjs/workflow";

/** The result produced by the ChargeCard activity. Replace with your own shape. */
export interface ChargeCardResult {
  readonly ok: boolean;
}

/**
 * The ChargeCard {@link Activity}. It receives an {@link AbortSignal} that is
 * aborted when the run is cancelled or the activity times out; honor it for any
 * long-running work. Pass this to `ctx.activity(chargeCardActivity, options)`.
 */
export const chargeCardActivity: Activity<ChargeCardResult> = async (
  signal: AbortSignal,
): Promise<ChargeCardResult> => {
  if (signal.aborted) {
    throw new Error("ChargeCard activity aborted before it started.");
  }

  // Perform the effectful work here.

  return { ok: true };
};
