// OrderProcessingWorkflow.ts — generated by `street make:workflow OrderProcessing`.
import { createWorkflow } from "@streetjs/workflow";
import type { WorkflowContext, WorkflowEngine } from "@streetjs/workflow";

/** Input accepted by the OrderProcessing workflow. Replace with your own fields. */
export interface OrderProcessingInput {
  readonly id: string;
}

/** Output produced when the OrderProcessing workflow completes. Replace as needed. */
export interface OrderProcessingOutput {
  readonly completed: boolean;
}

/**
 * The registered name of this workflow. Pass it to `engine.run(ORDER_PROCESSING_WORKFLOW, ...)`
 * or to the `workflow:run` CLI command to start a run.
 */
export const ORDER_PROCESSING_WORKFLOW = "order-processing" as const;

/**
 * The imperative OrderProcessing Workflow_Function. Orchestrate durable work by
 * awaiting `ctx` members (activities, timers, pillar bridges); every effectful
 * call is journaled and replayed so the run survives process restarts.
 */
export async function orderProcessingWorkflow(
  ctx: WorkflowContext,
  input: OrderProcessingInput,
): Promise<OrderProcessingOutput> {
  ctx.logger.info("order-processing started", { id: input.id });

  // Run durable work through activities, for example:
  //   const result = await ctx.activity(async () => doWork(input));

  return { completed: true };
}

/**
 * Build a {@link WorkflowEngine} with the OrderProcessing workflow registered.
 * Application code should call this once during startup and share the engine.
 */
export function createOrderProcessingWorkflow(): WorkflowEngine {
  const engine = createWorkflow();
  engine.define<OrderProcessingInput, OrderProcessingOutput>(ORDER_PROCESSING_WORKFLOW, orderProcessingWorkflow);
  return engine;
}
