// src/repositories/widget.repository.ts
// Widget repository — auto-generated by street generate.

import { Injectable, container, PgPool } from 'streetjs';
import type { Widget } from '../services/widget.service.js';

const TABLE_NAME = 'widgets';

@Injectable()
export class WidgetRepository {
  private readonly pool = container.resolve(PgPool);

  async findAll(page: number, limit: number): Promise<{ items: Widget[]; total: number }> {
    const offset = (page - 1) * limit;

    const [dataResult, countResult] = await Promise.all([
      this.pool.query(
        `SELECT * FROM ${TABLE_NAME} ORDER BY created_at DESC LIMIT $1 OFFSET $2`,
        [limit, offset]
      ),
      this.pool.query(`SELECT COUNT(*) AS total FROM ${TABLE_NAME}`),
    ]);

    const items = dataResult.rows as Widget[];
    const total = parseInt(String(countResult.rows[0]?.['total'] ?? '0'), 10);

    return { items, total };
  }

  async findById(id: string): Promise<Widget | null> {
    const result = await this.pool.query(
      `SELECT * FROM ${TABLE_NAME} WHERE id = $1`,
      [id]
    );
    return (result.rows[0] as Widget) ?? null;
  }

  async create(item: Widget): Promise<void> {
    const keys = Object.keys(item);
    const columns = keys.join(', ');
    const values = keys.map((_, i) => `$${i + 1}`).join(', ');
    const params = keys.map((k) => item[k]);

    await this.pool.query(
      `INSERT INTO ${TABLE_NAME} (${columns}) VALUES (${values})`,
      params
    );
  }

  async update(item: Widget): Promise<void> {
    const keys = Object.keys(item).filter((k) => k !== 'id');
    const setClause = keys.map((k, i) => `${k} = $${i + 1}`).join(', ');
    const params = [...keys.map((k) => item[k]), item.id];

    await this.pool.query(
      `UPDATE ${TABLE_NAME} SET ${setClause} WHERE id = $${keys.length + 1}`,
      params
    );
  }

  async delete(id: string): Promise<void> {
    await this.pool.query(`DELETE FROM ${TABLE_NAME} WHERE id = $1`, [id]);
  }
}
