// src/channels/GeneralChannel.ts
// GeneralChannel — auto-generated by `street make:channel`.
//
// A strongly-typed channel definition that binds a typed message union to a
// room, so consumers get compile-time checking of broadcast payloads.

import { type Room, type RealtimeMessage } from '@streetjs/realtime';

/** Typed messages carried by the "general" channel. */
export type GeneralMessage =
  | RealtimeMessage<{ text: string }>;

/** Strongly-typed handle factory for the "general" channel. */
export class GeneralChannel {
  /** The stable channel name this handle broadcasts to. */
  static readonly channelName = 'general' as const;

  constructor(private readonly room: Room) {}

  /** Deliver a typed {@link GeneralMessage} to every member of the room. */
  broadcast(message: GeneralMessage): Promise<void> {
    return this.room.broadcast(message);
  }
}
