// src/cli/generators.ts
// @streetjs/workflow — code generators for `make:workflow` and `make:activity`.
//
// Validate a name and emit a typed scaffold that imports only public
// `@streetjs/workflow` symbols and compiles under `tsc` with no errors
// (Requirements 24.2, 31.4). Name validation and template rendering are PURE:
// they perform NO filesystem access and simply return the target path plus the
// generated source. The command layer (Task 18.2) performs the guarded write.
// This mirrors the `@streetjs/storage` cli/generators.ts pattern.

import { join } from "node:path";

/** The outcome of a generator invocation. */
export interface GenerateResult {
  /** Path of the file that would be written by the command layer. */
  path: string;
  /** The generated source content. */
  contents: string;
}

/** A generator name must be an identifier-safe PascalCase token. */
const IDENTIFIER_RE = /^[A-Za-z][A-Za-z0-9]*$/;

/** Default output directory for `make:workflow` scaffolds. */
export const DEFAULT_WORKFLOW_DIR = "./workflows";

/** Default output directory for `make:activity` scaffolds. */
export const DEFAULT_ACTIVITY_DIR = "./activities";

/** Validate a `make:workflow`/`make:activity` name (identifier-safe). */
export function isValidGeneratorName(name: string): boolean {
  return typeof name === "string" && IDENTIFIER_RE.test(name);
}

function assertValidName(name: string): void {
  if (!isValidGeneratorName(name)) {
    throw new Error(
      `Invalid generator name: "${name}". Use a PascalCase identifier ` +
        `(a letter followed by letters or digits, e.g. "OrderProcessing").`,
    );
  }
}

/** Normalize an identifier so its first character is upper-cased (PascalCase). */
function toClassName(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/** Lower-case the first character of a PascalCase token (camelCase). */
function toCamelCase(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

/** Convert a PascalCase token to kebab-case, e.g. `OrderProcessing` → `order-processing`. */
function toKebabCase(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

/** Convert a PascalCase token to SCREAMING_SNAKE_CASE. */
function toConstantCase(name: string): string {
  return toKebabCase(name).replace(/-/g, "_").toUpperCase();
}

/**
 * Generate a workflow module scaffold: a typed imperative `Workflow_Function`
 * plus a factory that registers it on an engine via {@link createWorkflow},
 * importing only the public `@streetjs/workflow` surface. Compiles cleanly under
 * the package's strict `tsc` (Requirements 24.2, 31.4).
 *
 * @param name - PascalCase identifier for the workflow (e.g. `OrderProcessing`).
 * @param dir - Output directory (defaults to {@link DEFAULT_WORKFLOW_DIR}).
 * @throws Error when `name` is not a valid identifier — validated before any
 *   output is produced. This function is PURE and performs no filesystem access.
 */
export function generateWorkflow(
  name: string,
  dir: string = DEFAULT_WORKFLOW_DIR,
): GenerateResult {
  // Validate BEFORE producing any output (pure, no filesystem).
  assertValidName(name);

  const className = toClassName(name);
  const fnName = `${toCamelCase(className)}Workflow`;
  const factoryName = `create${className}Workflow`;
  const inputType = `${className}Input`;
  const outputType = `${className}Output`;
  const registeredName = toKebabCase(className);
  const nameConst = `${toConstantCase(className)}_WORKFLOW`;
  const path = join(dir, `${className}Workflow.ts`);

  const contents = `// ${className}Workflow.ts — generated by \`street make:workflow ${name}\`.
import { createWorkflow } from "@streetjs/workflow";
import type { WorkflowContext, WorkflowEngine } from "@streetjs/workflow";

/** Input accepted by the ${className} workflow. Replace with your own fields. */
export interface ${inputType} {
  readonly id: string;
}

/** Output produced when the ${className} workflow completes. Replace as needed. */
export interface ${outputType} {
  readonly completed: boolean;
}

/**
 * The registered name of this workflow. Pass it to \`engine.run(${nameConst}, ...)\`
 * or to the \`workflow:run\` CLI command to start a run.
 */
export const ${nameConst} = "${registeredName}" as const;

/**
 * The imperative ${className} Workflow_Function. Orchestrate durable work by
 * awaiting \`ctx\` members (activities, timers, pillar bridges); every effectful
 * call is journaled and replayed so the run survives process restarts.
 */
export async function ${fnName}(
  ctx: WorkflowContext,
  input: ${inputType},
): Promise<${outputType}> {
  ctx.logger.info("${registeredName} started", { id: input.id });

  // Run durable work through activities, for example:
  //   const result = await ctx.activity(async () => doWork(input));

  return { completed: true };
}

/**
 * Build a {@link WorkflowEngine} with the ${className} workflow registered.
 * Application code should call this once during startup and share the engine.
 */
export function ${factoryName}(): WorkflowEngine {
  const engine = createWorkflow();
  engine.define<${inputType}, ${outputType}>(${nameConst}, ${fnName});
  return engine;
}
`;
  return { path, contents };
}

/**
 * Generate an activity module scaffold: a typed {@link Activity} that honors its
 * {@link AbortSignal}, importing only the public `@streetjs/workflow` surface.
 * Compiles cleanly under the package's strict `tsc` (Requirements 24.2, 31.4).
 *
 * @param name - PascalCase identifier for the activity (e.g. `ChargeCard`).
 * @param dir - Output directory (defaults to {@link DEFAULT_ACTIVITY_DIR}).
 * @throws Error when `name` is not a valid identifier — validated before any
 *   output is produced. This function is PURE and performs no filesystem access.
 */
export function generateActivity(
  name: string,
  dir: string = DEFAULT_ACTIVITY_DIR,
): GenerateResult {
  // Validate BEFORE producing any output (pure, no filesystem).
  assertValidName(name);

  const className = toClassName(name);
  const activityName = `${toCamelCase(className)}Activity`;
  const resultType = `${className}Result`;
  const path = join(dir, `${className}Activity.ts`);

  const contents = `// ${className}Activity.ts — generated by \`street make:activity ${name}\`.
import type { Activity } from "@streetjs/workflow";

/** The result produced by the ${className} activity. Replace with your own shape. */
export interface ${resultType} {
  readonly ok: boolean;
}

/**
 * The ${className} {@link Activity}. It receives an {@link AbortSignal} that is
 * aborted when the run is cancelled or the activity times out; honor it for any
 * long-running work. Pass this to \`ctx.activity(${activityName}, options)\`.
 */
export const ${activityName}: Activity<${resultType}> = async (
  signal: AbortSignal,
): Promise<${resultType}> => {
  if (signal.aborted) {
    throw new Error("${className} activity aborted before it started.");
  }

  // Perform the effectful work here.

  return { ok: true };
};
`;
  return { path, contents };
}
