// src/cli/generators.ts
// @streetjs/storage — code generators for `make:storage`.
//
// Validate a name, refuse to overwrite an existing target, and emit a typed
// scaffold that imports only public `@streetjs/storage` symbols and compiles
// under `tsc`. Name validation and template rendering are pure (no filesystem),
// so they are trivially unit-testable; `writeScaffold` performs the guarded
// write. This mirrors the `@streetjs/events` cli/generators.ts pattern.
//
// Requirement 21.2: `make:storage` produces TypeScript source that compiles
// with `tsc` without errors.

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

/** The outcome of a generator invocation. */
export interface GenerateResult {
  /** Path of the file that was (or would be) written. */
  path: string;
  /** The generated source content. */
  contents: string;
}

/** A generator name must be an identifier-safe PascalCase token. */
const IDENTIFIER_RE = /^[A-Za-z][A-Za-z0-9]*$/;

/** Default output directory for `make:storage` scaffolds. */
export const DEFAULT_STORAGE_DIR = "./storage";

/** The built-in, zero-dependency providers a scaffold may target directly. */
const BUILT_IN_PROVIDERS = ["memory", "local"] as const;

/** A zero-dependency provider name accepted by {@link generateStorage}. */
export type BuiltInProvider = (typeof BUILT_IN_PROVIDERS)[number];

/** Validate a `make:storage` name (identifier-safe). */
export function isValidGeneratorName(name: string): boolean {
  return typeof name === "string" && IDENTIFIER_RE.test(name);
}

/** Validate a scaffold provider against the built-in zero-dependency set. */
export function isValidProvider(provider: string): provider is BuiltInProvider {
  return (BUILT_IN_PROVIDERS as readonly string[]).includes(provider);
}

function toClassName(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function assertValidName(name: string): void {
  if (!isValidGeneratorName(name)) {
    throw new Error(
      `Invalid generator name: "${name}". Use a PascalCase identifier ` +
        `(a letter followed by letters or digits, e.g. "Uploads").`,
    );
  }
}

function assertValidProvider(provider: string): void {
  if (!isValidProvider(provider)) {
    throw new Error(
      `Invalid storage provider: "${provider}". Use a built-in zero-dependency ` +
        `provider (${BUILT_IN_PROVIDERS.map((p) => `"${p}"`).join(" or ")}).`,
    );
  }
}

/**
 * Render the provider-specific `StorageConfig` literal body. The `local`
 * provider requires a `root` directory, so the scaffold supplies a sensible
 * default that keeps the emitted module compiling and runnable out of the box.
 */
function renderConfigBody(provider: BuiltInProvider, className: string): string {
  if (provider === "local") {
    return `    provider: "local",
    // The local filesystem driver persists objects beneath this directory.
    root: "./var/${className.toLowerCase()}",`;
  }
  return `    provider: "memory",`;
}

/**
 * Generate a storage module scaffold: a typed factory that builds a
 * {@link Storage} instance through {@link createStorage}, importing only the
 * public `@streetjs/storage` surface. Compiles cleanly under `tsc`
 * (Requirement 21.2).
 *
 * @param name - PascalCase identifier for the storage module.
 * @param dir - Output directory (defaults to {@link DEFAULT_STORAGE_DIR}).
 * @param provider - A built-in zero-dependency provider (`memory` or `local`);
 *   defaults to `memory` so the scaffold runs without configuration.
 * @throws Error when `name` is not a valid identifier or `provider` is not a
 *   built-in zero-dependency provider — validated before any output is produced.
 */
export function generateStorage(
  name: string,
  dir: string = DEFAULT_STORAGE_DIR,
  provider: BuiltInProvider = "memory",
): GenerateResult {
  // Validate every input BEFORE producing any output (pure, no filesystem).
  assertValidName(name);
  assertValidProvider(provider);

  const className = toClassName(name);
  const factoryName = `create${className}Storage`;
  const configName = `${className.charAt(0).toLowerCase()}${className.slice(1)}StorageConfig`;
  const path = join(dir, `${className}Storage.ts`);
  const contents = `// ${className}Storage.ts — generated by \`street make:storage ${name}\`.
import { createStorage } from "@streetjs/storage";
import type { Storage, StorageConfig } from "@streetjs/storage";

/**
 * Configuration for the ${className} storage module. Backed by the built-in
 * zero-dependency "${provider}" provider so it runs without external services.
 * Switch \`provider\` (and supply a pre-constructed \`driver\` for cloud
 * providers) to change the backend without touching call sites.
 */
export const ${configName}: StorageConfig = {
${renderConfigBody(provider, className)}
};

/**
 * Build the ${className} {@link Storage} instance. Application code should call
 * this once during startup and share the returned facade.
 *
 * Use it:
 *   const storage = ${factoryName}();
 *   await storage.put("hello.txt", "world");
 */
export function ${factoryName}(): Storage {
  return createStorage(${configName});
}
`;
  return { path, contents };
}

/**
 * Write a generated scaffold to disk, refusing to overwrite an existing target
 * and creating a fresh file otherwise. The parent directory is created as
 * needed; the `wx` flag makes the no-overwrite check atomic.
 *
 * @throws Error when the target file already exists.
 */
export function writeScaffold(result: GenerateResult): void {
  if (existsSync(result.path)) {
    throw new Error(`Refusing to overwrite existing file: ${result.path}`);
  }
  mkdirSync(dirname(result.path), { recursive: true });
  writeFileSync(result.path, result.contents, { encoding: "utf8", flag: "wx" });
}
