// src/tests/captions-waveform.test.ts
// Pure-function coverage for WebVTT caption building and waveform peak
// extraction. No ffmpeg/ffprobe, no I/O.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  buildWebVtt,
  formatVttTimestamp,
  buildWaveformArgs,
  computeWaveformPeaks,
  MediaValidationError,
  type TranscriptCue,
} from '../index.js';

// ── formatVttTimestamp ─────────────────────────────────────────────────────────

test('formatVttTimestamp formats seconds as HH:MM:SS.mmm', () => {
  assert.equal(formatVttTimestamp(0), '00:00:00.000');
  assert.equal(formatVttTimestamp(1.5), '00:00:01.500');
  assert.equal(formatVttTimestamp(61.25), '00:01:01.250');
  assert.equal(formatVttTimestamp(3661.001), '01:01:01.001');
  // Rounds to the nearest millisecond.
  assert.equal(formatVttTimestamp(1.23449), '00:00:01.234');
});

test('formatVttTimestamp rejects negative / non-finite input', () => {
  assert.throws(() => formatVttTimestamp(-1), MediaValidationError);
  assert.throws(() => formatVttTimestamp(Number.NaN), MediaValidationError);
  assert.throws(() => formatVttTimestamp(Number.POSITIVE_INFINITY), MediaValidationError);
});

// ── buildWebVtt ────────────────────────────────────────────────────────────────

test('buildWebVtt builds a valid document from ordered cues', () => {
  const cues: TranscriptCue[] = [
    { start: 0, end: 1.5, text: 'Hello world' },
    { start: 1.5, end: 3, text: 'second line', id: 'c2' },
  ];
  const vtt = buildWebVtt(cues);
  assert.equal(
    vtt,
    [
      'WEBVTT',
      '',
      '00:00:00.000 --> 00:00:01.500',
      'Hello world',
      '',
      'c2',
      '00:00:01.500 --> 00:00:03.000',
      'second line',
      '',
    ].join('\n'),
  );
});

test('buildWebVtt emits a header NOTE and normalizes CRLF in text', () => {
  const vtt = buildWebVtt([{ start: 0, end: 1, text: 'a\r\nb' }], { header: 'auto-generated\nby streetjs' });
  assert.match(vtt, /^WEBVTT\nNOTE auto-generated by streetjs\n/);
  assert.match(vtt, /a\nb\n$/);
});

test('buildWebVtt yields a header-only file for no cues and ends with a newline', () => {
  assert.equal(buildWebVtt([]), 'WEBVTT\n');
});

test('buildWebVtt validates cue shape and ordering', () => {
  assert.throws(() => buildWebVtt(null as unknown as TranscriptCue[]), MediaValidationError);
  assert.throws(() => buildWebVtt([{ start: -1, end: 1, text: 'x' }]), /start must be >= 0/);
  assert.throws(() => buildWebVtt([{ start: 2, end: 1, text: 'x' }]), /end .* must be >= start/);
  assert.throws(() => buildWebVtt([{ start: 0, end: Number.NaN, text: 'x' }]), /finite/);
  assert.throws(
    () =>
      buildWebVtt([
        { start: 5, end: 6, text: 'a' },
        { start: 1, end: 2, text: 'b' },
      ]),
    /must be ordered/,
  );
});

// ── buildWaveformArgs ──────────────────────────────────────────────────────────

test('buildWaveformArgs decodes to mono s16le PCM on stdout', () => {
  const args = buildWaveformArgs('in.mp4');
  assert.deepEqual(args, [
    '-hide_banner', '-v', 'error', '-i', 'in.mp4',
    '-vn', '-ac', '1', '-ar', '8000', '-f', 's16le', 'pipe:1',
  ]);
  assert.deepEqual(buildWaveformArgs('in.mp4', { sampleRate: 16000 }).slice(-4), ['16000', '-f', 's16le', 'pipe:1']);
});

test('buildWaveformArgs validates input + sampleRate', () => {
  assert.throws(() => buildWaveformArgs(''), /input path is required/);
  assert.throws(() => buildWaveformArgs('in.mp4', { sampleRate: 0 }), /positive integer/);
  assert.throws(() => buildWaveformArgs('in.mp4', { sampleRate: 1.5 }), /positive integer/);
});

// ── computeWaveformPeaks ───────────────────────────────────────────────────────

/** Build a mono s16le PCM buffer from signed sample values. */
function pcm(...samples: number[]): Uint8Array {
  const buf = new Uint8Array(samples.length * 2);
  const view = new DataView(buf.buffer);
  samples.forEach((s, i) => view.setInt16(i * 2, s, true));
  return buf;
}

test('computeWaveformPeaks reduces PCM to normalized absolute-max buckets', () => {
  // 4 samples → 2 buckets: [max(|0|,|16384|), max(|-32768|,|8192|)].
  const wf = computeWaveformPeaks(pcm(0, 16384, -32768, 8192), { buckets: 2 });
  assert.equal(wf.version, 1);
  assert.equal(wf.channels, 1);
  assert.equal(wf.bucketCount, 2);
  assert.equal(wf.peaks.length, 2);
  assert.ok(Math.abs(wf.peaks[0]! - 0.5) < 1e-9);
  assert.ok(Math.abs(wf.peaks[1]! - 1) < 1e-9); // 32768/32768
});

test('computeWaveformPeaks handles empty PCM and odd trailing bytes', () => {
  assert.deepEqual(computeWaveformPeaks(new Uint8Array(0), { buckets: 8 }), {
    version: 1, channels: 1, bucketCount: 0, peaks: [],
  });
  // 3 bytes → one whole sample (value 0), trailing byte ignored.
  const wf = computeWaveformPeaks(new Uint8Array([0, 0, 127]), { buckets: 4 });
  assert.equal(wf.bucketCount, 1);
});

test('computeWaveformPeaks truncates buckets to sample count and echoes sampleRate', () => {
  const wf = computeWaveformPeaks(pcm(100, -200), { buckets: 10, sampleRate: 8000 });
  assert.equal(wf.bucketCount, 2); // fewer samples than requested buckets
  assert.equal(wf.sampleRate, 8000);
});

test('computeWaveformPeaks validates buckets', () => {
  assert.throws(() => computeWaveformPeaks(pcm(1), { buckets: 0 }), /positive integer/);
  assert.throws(() => computeWaveformPeaks(pcm(1), { buckets: -3 }), /positive integer/);
});
