// src/cli/generators.ts
// @streetjs/gateway — code generators for `make:gateway-route` and `make:proxy`.
//
// Validate a name and emit a typed scaffold that imports only public
// `@streetjs/gateway` symbols and compiles under `tsc` with no errors. Name
// validation and template rendering are PURE: they perform NO filesystem access
// and simply return the target path plus the generated source. The command layer
// (commands.ts) performs the guarded write. This mirrors the sibling
// `packages/workflow/src/cli/generators.ts` pattern.

import { join } from "node:path";

/** The outcome of a generator invocation. */
export interface GenerateResult {
  /** Path of the file that would be written by the command layer. */
  path: string;
  /** The generated source content. */
  contents: string;
}

/** A generator name must be an identifier-safe PascalCase token. */
const IDENTIFIER_RE = /^[A-Z][A-Za-z0-9]*$/;

/** Default output directory for `make:gateway-route` scaffolds. */
export const DEFAULT_ROUTE_DIR = "./routes";

/** Default output directory for `make:proxy` scaffolds. */
export const DEFAULT_PROXY_DIR = "./gateways";

/**
 * Validate a `make:gateway-route`/`make:proxy` name: an identifier-safe
 * PascalCase token (an upper-case letter followed by letters or digits).
 */
export function isValidGeneratorName(name: string): boolean {
  return typeof name === "string" && IDENTIFIER_RE.test(name);
}

/**
 * Assert that `name` is a valid PascalCase identifier, throwing a descriptive
 * {@link Error} otherwise. PURE — performs no filesystem access.
 *
 * @throws Error when `name` is not a PascalCase identifier.
 */
export function assertValidName(name: string): void {
  if (!isValidGeneratorName(name)) {
    throw new Error(
      `Invalid generator name: "${name}". Use a PascalCase identifier ` +
        `(an upper-case letter followed by letters or digits, e.g. "UsersApi").`,
    );
  }
}

/** Lower-case the first character of a PascalCase token (camelCase). */
function toCamelCase(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

/** Convert a PascalCase token to kebab-case, e.g. `UsersApi` → `users-api`. */
function toKebabCase(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

/**
 * Generate a typed {@link RouteConfig} module scaffold, importing only the public
 * `@streetjs/gateway` type surface. The generated source compiles cleanly under
 * the package's strict `tsc`.
 *
 * @param name - PascalCase identifier for the route (e.g. `UsersApi`).
 * @param dir - Output directory (defaults to {@link DEFAULT_ROUTE_DIR}).
 * @throws Error when `name` is not a valid identifier — validated before any
 *   output is produced. This function is PURE and performs no filesystem access.
 */
export function generateGatewayRoute(
  name: string,
  dir: string = DEFAULT_ROUTE_DIR,
): GenerateResult {
  // Validate BEFORE producing any output (pure, no filesystem).
  assertValidName(name);

  const routeConst = `${toCamelCase(name)}Route`;
  const serviceName = toKebabCase(name);
  const pattern = `/${serviceName}/*`;
  const path = join(dir, `${name}Route.ts`);

  const contents = `// ${name}Route.ts — generated by \`street make:gateway-route ${name}\`.
import type { RouteConfig } from "@streetjs/gateway";

/**
 * The ${name} route. Register it in a {@link GatewayConfig}'s \`routes\` array so
 * matching requests are forwarded to the "${serviceName}" upstream service.
 * Adjust the pattern, methods, and per-route policy to taste.
 */
export const ${routeConst}: RouteConfig = {
  id: "${serviceName}",
  pattern: "${pattern}",
  kind: "prefix",
  methods: ["GET", "POST", "PUT", "PATCH", "DELETE"],
  service: "${serviceName}",
  strategy: "round-robin",
  policy: {
    timeoutMs: 30_000,
    retry: { maxAttempts: 2 },
  },
};
`;
  return { path, contents };
}

/**
 * Generate a small proxy/gateway setup module scaffold: a factory that wires a
 * {@link createGateway} call from a typed {@link GatewayConfig}, importing only
 * the public `@streetjs/gateway` surface. Compiles cleanly under the package's
 * strict `tsc`.
 *
 * @param name - PascalCase identifier for the gateway (e.g. `Edge`).
 * @param dir - Output directory (defaults to {@link DEFAULT_PROXY_DIR}).
 * @throws Error when `name` is not a valid identifier — validated before any
 *   output is produced. This function is PURE and performs no filesystem access.
 */
export function generateProxy(
  name: string,
  dir: string = DEFAULT_PROXY_DIR,
): GenerateResult {
  // Validate BEFORE producing any output (pure, no filesystem).
  assertValidName(name);

  const factoryName = `create${name}Gateway`;
  const configConst = `${toCamelCase(name)}GatewayConfig`;
  const serviceName = toKebabCase(name);
  const pattern = `/${serviceName}/*`;
  const path = join(dir, `${name}Gateway.ts`);

  const contents = `// ${name}Gateway.ts — generated by \`street make:proxy ${name}\`.
import { createGateway } from "@streetjs/gateway";
import type { Gateway, GatewayConfig } from "@streetjs/gateway";

/**
 * The ${name} gateway configuration: a single "${serviceName}" service behind one
 * prefix route. Replace the target URLs and add routes/services as needed.
 */
export const ${configConst}: GatewayConfig = {
  services: [
    {
      name: "${serviceName}",
      targets: [{ id: "${serviceName}-1", url: "http://127.0.0.1:8081" }],
      strategy: "round-robin",
    },
  ],
  routes: [
    {
      id: "${serviceName}",
      pattern: "${pattern}",
      kind: "prefix",
      service: "${serviceName}",
    },
  ],
};

/**
 * Build the ${name} {@link Gateway}. Call this once during startup and share the
 * returned gateway; drive requests through \`gateway.handle(req)\`.
 */
export function ${factoryName}(): Gateway {
  return createGateway(${configConst});
}
`;
  return { path, contents };
}
